version: "3.7"

services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    image: remi
    container_name: remi_slim
    volumes:
#     - /host/path:/container/path
      - /app/data/remi:/app/data
      - /app/data/remi/logs:/app/logs
    network_mode: bridge
    ports:
#     - localPort:containerPort
      - "4001:5000"
    environment:
      DB_HOST: 'host.docker.internal'
      DB_USER: 'remi'
      DB_PASSWORD: 'Mi_Secreto0'
      DB_PORT: '3306'
      DB_NAME: 'remi'
    extra_hosts:
      - "host.docker.internal:host-gateway"

