FROM python:3.8.13-alpine

RUN apk -U upgrade \
    && apk add bash gcc libc-dev libffi-dev python3-dev\
    && pip3 install --upgrade pip

WORKDIR /app

COPY . /app

RUN pip3 --no-cache-dir install -r requirements.txt

CMD ["gunicorn", "--bind=0.0.0.0:5000", "app:app"]