version: "3.7"

services:

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    image: remi
    container_name: remi_slim
    volumes:
      - /data:/app/data
    network_mode: bridge
    ports:
      - 5000:5000
    environment:
      DB_HOST: 'host.docker.internal'
    extra_hosts:
      - "host.docker.internal:host-gateway"

