"""empty message

Revision ID: d99cd2207689
Revises: 
Create Date: 2022-04-15 19:09:55.910806

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import oracle

# revision identifiers, used by Alembic.
revision = 'd99cd2207689'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remi_taxpayers',
    sa.Column('id', sa.Integer(), sa.Identity(always=False, start=1), nullable=False),
    sa.Column('identification', sa.String(20), nullable=False),
    sa.Column('business_name', sa.String(500), nullable=False),
    sa.Column('trade_name', sa.String(500), nullable=True),
    sa.Column('address', sa.String(500), nullable=False),
    sa.Column('status', sa.String(20), nullable=False),
    sa.Column('observation', sa.String(500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table('remi_taxpayers')
    # ### end Alembic commands ###
